### PR TITLE
Fixes cors and userid problems

### LINKED ISSUE #40: Cors error and mismatching data types for userid
As of now we need to disable CORS in browser

Fetching UserId doesn't work as it tries to convert from/to Long

### PR DESCRIPTION
**Pull request by amyrman**
Fixes #40

### CODE REVIEW

File: backend/src/main/java/com/example/parkingspot/SecurityConfig.java [hunk 1]
```diff
@@ -9,15 +11,26 @@
...
 import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
 import org.springframework.security.web.SecurityFilterChain;
+import org.springframework.web.cors.CorsConfiguration;
+import org.springframework.web.cors.CorsConfigurationSource;
+import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
 
 @Configuration
 public class SecurityConfig {
 
+  @Bean CorsConfigurationSource corsConfigurationSource() {
```
Comment (stratosfloor) [inline backend/src/main/java/com/example/parkingspot/SecurityConfig.java:21]: Nice config for cors!

**Review by stratosfloor — APPROVED** [review]

File: backend/src/main/java/com/example/parkingspot/controller/EventController.java [hunk 2]
```diff
@@ -17,30 +19,33 @@
...
 
-  @GetMapping("/{id}")
-  public ResponseEntity<Event> getEventById(@PathVariable("id") Long eventId) {
-    Event foundEvent = eventService.fetchEventById(eventId);
+  @GetMapping()
+  public ResponseEntity <List<Event>> getEventById() {
+    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
+    String username = auth.getName();
+    var userId = userService.getUserId(username);
+    var foundEvent = eventService.fetchEventByUserId(userId);
```
Comment (christerresin) [inline backend/src/main/java/com/example/parkingspot/controller/EventController.java:46]: Nice use of SecurityContextHolder instead of glued solution with token and localstorage

File: frontend/src/component/cars.js [hunk 3]
```diff
@@ -25,26 +47,39 @@ function Cars() {
...
-            {cars.map((car) => (
-              <li key={car.id} className='cars_list_item'>
-                {car.registration}
-              </li>
-            ))}
-          </ul>
-        </div>
-      ) : (
-        <div></div>
-      )}
```
Comment (christerresin) [inline frontend/src/component/cars.js:47]: Great refactor since backend now always returns a list

**Review by christerresin — APPROVED** [review]
